// session events
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REFRESH_TOKEN = 'REFRESH_TOKEN_SUCCESS';

// playback events
export const FETCH_TRACK_DATA_SUCCESS = 'FETCH_TRACK_DATA_SUCCESS';
export const PREVIOUS_TRACK_SUCCESS = 'PREVIOUS_TRACK_SUCCESS';
export const RESUME_PLAYBACK_SUCCESS = 'RESUME_PLAYBACK_SUCCESS';
export const PAUSE_PLAYBACK_SUCCESS = 'PAUSE_PLAYBACK_SUCCESS';
export const SKIP_TRACK_SUCCESS = 'SKIP_TRACK_SUCCESS';
export const SEEK_TRACK_SUCCESS = 'SEEK_TRACK_SUCCESS';
