// session events
export const LOGIN = 'LOGIN';
export const LOAD = 'LOAD';
export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// playback events
export const FETCH_TRACK_DATA_SUCCESS = 'FETCH_TRACK_DATA_SUCCESS';
export const FETCH_TRACK_PROGRESS_SUCCESS = 'FETCH_TRACK_PROGRESS_SUCCESS';
export const PREVIOUS_TRACK_SUCCESS = 'PREVIOUS_TRACK_SUCCESS';
export const RESUME_PLAYBACK_SUCCESS = 'RESUME_PLAYBACK_SUCCESS';
export const PAUSE_PLAYBACK_SUCCESS = 'PAUSE_PLAYBACK_SUCCESS';
export const SKIP_TRACK_SUCCESS = 'SKIP_TRACK_SUCCESS';
export const SEEK_TRACK_SUCCESS = 'SEEK_TRACK_SUCCESS';

// search events
export const SEARCH_TRACK = 'SEARCH_TRACK';
export const SEARCH_TRACK_SUCCESS = 'SEARCH_TRACK_SUCCESS';

export const UPDATE_USERS = 'UPDATE_USERS';
export const ADD_USER = 'ADD_USER';
